name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Display lines of code changed
          plugin_lines: yes
          
          # Display most used languages with percentage details
          plugin_languages: yes
          plugin_languages_details: percentage
          
          # Display number of page views
          plugin_traffic: yes
          
          # Display blog post
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_user: realsale
